name: Run Bash Commands

on:
  #push:
  #  branches: ["main"]   # Trigger on push to main
  workflow_dispatch:     # Allow manual run from Actions tab

jobs:
  run-bash:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'github-actions[bot]' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Bash commands
        run: |
          find . -type f -not -path "*/.git*" -exec sed -i "s|href="/"|href="./"|g" {} +
          find . -type f -not -path "*/.git*" -exec sed -i "s|src="/"|src="./"|g" {} +

          grep -nr --exclude-dir='.git' --exclude-dir='.github' 'href="/"'      && sleep 10 || echo "NOTFOUND href/"
          grep -nr --exclude-dir='.git' --exclude-dir='.github' 'src="/"'       && sleep 10 || echo "NOTFOUND slash src/"
          grep -nr --exclude-dir='.git' --exclude-dir='.github' 'src="/about"'  && sleep 10 || echo "NOTFOUND /about"

          dirs2process=('/assets' '/credits' '/style-guide')

          # DEBUG block #
          for _dir in ${dirs2process[*]} ;do
            grep -nrw "[^.]/${_dir}" --exclude-dir='.git' --exclude-dir='.github' && \
              sleep 10                                                            || \
              echo -e "\n\t🟢 Did not found/grep: ${_dir}"
          done

          for _dir in ${dirs2process[*]} ;do
            find . -type f -not -path "*/.git*" -exec sed -i "s|${_dir}|.${_dir}|g" {} +
          done

          for _dir in ${dirs2process[*]} ;do
            grep -nrw "[^.]/${_dir}" --exclude-dir='.git' --exclude-dir='.github' && \
              echo -e "\n\t🔴 Found/grep something in: ${_dir}"                   || \
              echo -e "\n\t🟢 Did not found/grep: ${_dir}"
          done

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "Auto-update: $(date)"
